name: Build on Ubuntu 22.04 with GCC (c++11)

on:
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_CXX_STANDARD=11

      - name: Build Examples
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --target all_examples

      - name: Build Tests
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --target all_tests

      - name: Run Tests
        working-directory: ${{github.workspace}}/build
        run: ctest -C ${{env.BUILD_TYPE}}

